### ISSUE TITLE
Add example configuration for rdap.nic.cz

### ISSUE THREAD

**Issue by tomhrr** [APNIC-net/rdap-conformance#30]

**Comment by ziima** [comment]
If you still need it, here's the config for our conformance tests (not production though):
https://github.com/CZ-NIC/fred-rdap/blob/master/test_cfg/conformance/rdap_conformance.json

**Comment by tomhrr** [comment]
Thanks for that.  (It turns out that a file for this was added on the same day as the issue, but the 'fix' tag was incorrect, so the issue was never closed.)
