### ISSUE TITLE
False negative access-control-allow-origin test

### ISSUE THREAD

**Issue by ziima** [APNIC-net/rdap-conformance#41]
According to the CORS specification https://www.w3.org/TR/cors/#resource-requests the `Access-Control-Allow-Origin` header needs to be added only to requests with `Origin` header. Since the `access-control-allow-origin` test doesn't send these headers, it can't reliably check, whether the CORS headers are added to the response.

**Comment by tomhrr** [comment]
Thanks, this has now been fixed (see f190a0a9e06ac8ebd834b2ff1f2d382efe109a92).
